<?php

/**
 * @file
 * Linkit hook implementations.
 */

use Drupal\Core\Form\FormStateInterface;


/**
 * Implements hook_form_FORM_ID_alter().
 */
function linkcustom_form_editor_link_dialog_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Alter only the form with ID 'editor_link_dialog'.
  if ($form_id !== 'editor_link_dialog') {
    return;
  }
  // Logs a notice
  $form['#attached']['library'][] = 'linkcustom/linkcustom.base';
}
